on:
  push:
    branches:
       - '**'
env:
  ENV_WORKFLOW: "env workflow"

jobs:
  display-variables:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.HOGE }}"
    - id: action
      uses: ./.github/actions/composite/
